import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Use - Sage',
  description: 'Sage Terms of Use - Understand your rights and responsibilities when using Sage.',
};

export default function TermsPage() {
  return (
    <main className="max-w-3xl mx-auto px-4 py-16">
      <div className="mb-8">
        <p className="text-xs uppercase tracking-wide text-emerald-700 mb-2">Legal</p>
        <h1 className="text-3xl font-semibold text-slate-900">Terms of Use</h1>
      </div>

      <div className="space-y-8 text-sm text-slate-700 leading-relaxed">
        <section>
          <p>
            By using Sage, you agree to these Terms of Use. Sage is currently in beta and under active development. 
            These terms explain how you can use the service, what we expect from users, and important limitations 
            to keep in mind.
          </p>
        </section>

        <div className="border-t border-slate-200 pt-8">
          <h2 className="text-xl font-semibold text-slate-900 mb-3">What Sage Does</h2>
          <p className="mb-3">
            Sage provides AI-generated career insights, suggestions, and feedback based on the information you provide, 
            including your resume, job descriptions, and answers to assessment questions. Our goal is to help you make 
            more informed career decisions.
          </p>
          <p>
            While Sage&apos;s outputs can be helpful, they are not perfect or definitive. AI-generated insights should be 
            used as guidance, not as the sole basis for important career decisions.
          </p>
        </div>

        <div className="border-t border-slate-200 pt-8">
          <h2 className="text-xl font-semibold text-slate-900 mb-3">Not Professional Advice</h2>
          <p className="mb-3 font-semibold">
            Sage does not provide legal, financial, HR, medical, or other professional advice.
          </p>
          <p className="mb-3">
            The insights and recommendations generated by Sage are for career guidance purposes only. They should 
            be evaluated using your own judgment and, when appropriate, in consultation with qualified professionals.
          </p>
          <p>
            You are solely responsible for your career decisions, job applications, and any actions you take based 
            on Sage&apos;s suggestions.
          </p>
        </div>

        <div className="border-t border-slate-200 pt-8">
          <h2 className="text-xl font-semibold text-slate-900 mb-3">Your Responsibilities</h2>
          <p className="mb-3">
            When using Sage, you agree to:
          </p>
          <ul className="list-disc pl-6 space-y-2">
            <li>Provide accurate information about yourself and your career goals</li>
            <li>Only upload or share content that you have the right to share (do not upload confidential company data, proprietary information, or content belonging to others)</li>
            <li>Use the service in good faith and not attempt to break, reverse engineer, or misuse it</li>
          </ul>
          <p className="mt-3">
            We reserve the right to restrict or terminate access for users who abuse the service or violate these terms.
          </p>
        </div>

        <div className="border-t border-slate-200 pt-8">
          <h2 className="text-xl font-semibold text-slate-900 mb-3">Acceptable Use</h2>
          <p className="mb-3">
            You may not use Sage for:
          </p>
          <ul className="list-disc pl-6 space-y-2">
            <li>Harassment, discrimination, or any harmful conduct</li>
            <li>Generating misleading, fraudulent, or deceptive resumes or job applications</li>
            <li>Any illegal purposes or activities</li>
          </ul>
        </div>

        <div className="border-t border-slate-200 pt-8">
          <h2 className="text-xl font-semibold text-slate-900 mb-3">Intellectual Property</h2>
          <p className="mb-3">
            The Sage product, including its branding, design, and user interface, is owned by us and protected by 
            applicable intellectual property laws.
          </p>
          <p className="mb-3">
            You retain ownership of your own content, including your resume and any information you provide to Sage. 
            However, by using Sage, you grant us permission to use your inputs and the outputs generated by the 
            service in an aggregated and anonymized way to improve the product.
          </p>
        </div>

        <div className="border-t border-slate-200 pt-8">
          <h2 className="text-xl font-semibold text-slate-900 mb-3">Beta, Availability & Changes</h2>
          <p className="mb-3">
            Sage is currently in beta. This means:
          </p>
          <ul className="list-disc pl-6 space-y-2 mb-3">
            <li>The service may change, pause, or be discontinued at any time</li>
            <li>There is no guarantee of uptime or uninterrupted access</li>
            <li>There may be bugs, errors, or limitations in functionality</li>
          </ul>
          <p>
            We may update features, pricing (if applicable in the future), and these Terms of Use as the product 
            evolves. When we make significant changes, we&apos;ll update the &quot;Last updated&quot; date below.
          </p>
        </div>

        <div className="border-t border-slate-200 pt-8">
          <h2 className="text-xl font-semibold text-slate-900 mb-3">Limitation of Liability</h2>
          <p className="mb-3">
            We are not liable for decisions you make based on Sage&apos;s suggestions or insights. Sage does not guarantee 
            any specific outcomes, such as getting a job, receiving a promotion, or achieving career success.
          </p>
          <p>
            To the fullest extent permitted by law, Sage is provided &quot;as is&quot; without warranties of any kind, either 
            express or implied. We are not responsible for any damages or losses arising from your use of the service.
          </p>
        </div>

        <div className="border-t border-slate-200 pt-8">
          <h2 className="text-xl font-semibold text-slate-900 mb-3">Contact</h2>
          <p>
            If you have questions about these Terms of Use, please contact us at{' '}
            <a 
              href="mailto:support@sagesays.ai" 
              className="text-emerald-700 hover:text-emerald-800 underline"
            >
              support@sagesays.ai
            </a>.
          </p>
        </div>

        <div className="border-t border-slate-200 pt-8">
          <p className="text-xs text-slate-500">
            Last updated: November 2025
          </p>
        </div>
      </div>
    </main>
  );
}
